//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleDetail
    {
        public Nullable<long> Users_Id { get; set; }
        public long Bike_Id { get; set; }
        public string Bike_Model { get; set; }
        public Nullable<long> Existing_Fuel { get; set; }
        public Nullable<long> Fuel_Refil { get; set; }
        public Nullable<long> Fuel_Left { get; set; }
        public Nullable<long> Amount_Paid { get; set; }
        public Nullable<long> Initial_Odometer_Reading { get; set; }
        public Nullable<long> Current_Odometer_Reading { get; set; }
    }
}
