//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public string Username { get; set; }
        public string Nepassword { get; set; }
        public string Repassword { get; set; }
        public long Mobile_No { get; set; }
    }
}
